server:
  port: 80


#开启服务降级
feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://116.62.128.176:7001/eureka/,http://116.62.128.176:7002/eureka/,http://116.62.128.176:7003/eureka/